refactor(refact): flyway is changed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,8 +42,9 @@ jobs:
 
     - name: Install Flyway
       run: |
-        curl -s https://api.flywaydb.org/flyway-commandline-8.5.13-linux-x64.tar.gz -o flyway.tar.gz
-        tar -xzf flyway.tar.gz
+        curl -LO https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.13/flyway-commandline-8.5.13-linux-x64.tar.gz
+        if [ $? -ne 0 ]; then echo "Error downloading Flyway"; exit 1; fi
+        tar -xzf flyway-commandline-8.5.13-linux-x64.tar.gz
         sudo mv flyway-*/flyway /usr/local/bin/
         flyway -v
         echo "Flyway installed."
